language: java
jdk: oraclejdk11
sudo: required
dist: trusty
group: edge

services:
  - mariadb
  - redis
addons:
  mariadb: '10.0'

before_install:
  - sudo mysql -e 'create database tasker;'
  - cp src/main/resources/application.yml.sample src/main/resources/application.yml
script:
  - ./mvnw clean install -B